### PR TITLE
Created test for RSpec

### PR DESCRIPTION
**Pull request by mariosknl**
Created RSpec test for different cases for my enumerable module. My partner Patrick Nyatindo and I worked for this project. We have worked together for creating the necessary code lines for testing.

### CODE REVIEW

**Comment by euqueme** [comment]
Hello @mariosknl :wave: 

I can't review your project because this is a collaborative project but I only see commits from you and not your coding partner, please add to the description of your pull request that both of you worked on the project or check the box that says you work alone in this project when you submit for a code review again. :memo: 

Happy coding! :rocket: 

PROJECT STATUS: INVALID :stop_sign:

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @mariosknl and @nyatindopatrick :balloon: :lollipop: 

### You've done an amazing job with this project, your test cases are well written and accomplished so you should feel very proud of yourselves :star: I noticed all your test cases are positive so the only change I would request is to add negative test cases to each describe block :construction: :construction_worker_man: :construction_worker_man: 

* [ ] specs cover positive and negative scenarios ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/commonsense.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/)) 

- To do this the description should be negative ('it doesn't do something') and you should use the .not_to method.

Example: you could change your false test cases with something like this
```ruby
.
.
  describe '#my_all?' do
.
.
    it 'doesn't return true if the array is falsy' do
      expect(boo.my_all?).not_to eq true
    end
.
.
  end
.
.
```

### That's it, team! :raised_hands: 

### Please :pray: make the changes :man_technologist: :man_technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work implementing the suggested changes :clap: :clap: However, I noticed some issues that you need to fix in order to get approval for the project. Check :arrow_down: 

- **[REQUIRED]** All linter checks should be successful :heavy_check_mark: . :pray: fix them
- **[OPTIONAL]** Since you wrote the tests, you can add info about the tests and how to run them in your Readme.md.

### That's it :relieved: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Review by whiz25 — APPROVED** [review]
## APPROVED! :clap:
Merge and proceed to the next project.

### Martin Afani

**Pull request merged**
